import type { InsertActivity, InsertTask } from "@shared/schema";

// Demo community plans with high-quality stock images
export const demoCommunityPlans = [
  {
    activity: {
      title: "Weekend Trip to Paris",
      description: "Complete 3-day Paris itinerary with sights, dining, and Eiffel Tower visit",
      category: "travel" as const,
      planSummary: "Romantic 3-day Paris escape with iconic landmarks, French cuisine, and evening river cruise",
      isPublic: true,
      shareTitle: "Weekend Trip to Paris",
      backdrop: "romantic_paris_citys_dfc7c798.jpg",
      tags: ["travel", "paris", "europe", "weekend", "romantic"],
      viewCount: 2400,
      likeCount: 2400,
      trendingScore: 4800,
      featuredInCommunity: true,
      creatorName: "Sarah Chen",
      creatorAvatar: null,
      status: "completed" as const,
    },
    tasks: [
      { title: "Book hotel in Le Marais district", description: "Boutique hotel near Metro", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Visit Eiffel Tower at sunset", description: "Book tickets in advance to skip lines", category: "travel", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Explore Louvre Museum", description: "See Mona Lisa and Egyptian exhibits", category: "travel", priority: "high" as const, timeEstimate: "4 hours" },
      { title: "Seine River dinner cruise", description: "Evening cruise with French dinner", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Stroll through Montmartre", description: "Visit Sacré-Cœur and artist square", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "30-Day Fitness Challenge",
      description: "Daily workouts, meal prep, and progress tracking for complete transformation",
      category: "health" as const,
      planSummary: "Structured 30-day fitness program with workouts, nutrition plan, and accountability tracking",
      isPublic: true,
      shareTitle: "30-Day Fitness Challenge",
      backdrop: "fitness_workout_gym__2325ee98.jpg",
      tags: ["fitness", "health", "workout", "challenge", "30days"],
      viewCount: 1800,
      likeCount: 1800,
      trendingScore: 3600,
      featuredInCommunity: true,
      creatorName: "Mike Johnson",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Week 1: Build foundation with bodyweight exercises", description: "Push-ups, squats, planks", category: "health", priority: "high" as const, timeEstimate: "45 min" },
      { title: "Meal prep healthy breakfast options", description: "Overnight oats, egg muffins, smoothie packs", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Week 2: Add resistance training", description: "Dumbbells and resistance bands", category: "health", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Track daily water intake (64oz)", description: "Use water tracking app", category: "health", priority: "medium" as const, timeEstimate: "5 min" },
      { title: "Weekly progress photos and measurements", description: "Track body composition changes", category: "health", priority: "medium" as const, timeEstimate: "10 min" },
    ]
  },
  {
    activity: {
      title: "Wedding Planning Checklist",
      description: "12-month wedding plan with venue, vendors, guests, and timeline",
      category: "personal" as const,
      planSummary: "Complete wedding planning guide covering venue booking, vendor selection, and timeline management",
      isPublic: true,
      shareTitle: "Wedding Planning Checklist",
      backdrop: "elegant_wedding_cere_9aa2c585.jpg",
      tags: ["wedding", "planning", "events", "checklist", "celebration"],
      viewCount: 3200,
      likeCount: 3200,
      trendingScore: 6400,
      featuredInCommunity: true,
      creatorName: "Emma Davis",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Set wedding budget and priorities", description: "Allocate funds across venue, catering, photography", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Book wedding venue (12 months out)", description: "Visit 3-5 venues, secure date", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Hire photographer and videographer", description: "Review portfolios, book 9-12 months ahead", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Finalize guest list and send save-the-dates", description: "Confirm addresses, design and mail STDs", category: "personal", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Schedule dress fittings and alterations", description: "Order dress 8-10 months out, fittings begin", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Career Switch to Tech",
      description: "6-month plan: coding bootcamp, portfolio projects, and job applications",
      category: "work" as const,
      planSummary: "Comprehensive career transition roadmap from non-tech to software development role",
      isPublic: true,
      shareTitle: "Career Switch to Tech",
      backdrop: "modern_tech_workspac_ef8fa108.jpg",
      tags: ["career", "tech", "coding", "bootcamp", "transition"],
      viewCount: 1500,
      likeCount: 1500,
      trendingScore: 3000,
      featuredInCommunity: false,
      creatorName: "Alex Kim",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Complete JavaScript fundamentals course", description: "FreeCodeCamp or Codecademy basics", category: "work", priority: "high" as const, timeEstimate: "40 hours" },
      { title: "Enroll in coding bootcamp (online or in-person)", description: "Research reviews, apply for scholarships", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Build 3 portfolio projects", description: "Full-stack apps showcasing skills", category: "work", priority: "high" as const, timeEstimate: "3 months" },
      { title: "Network with developers on LinkedIn", description: "Join tech communities, attend meetups", category: "work", priority: "medium" as const, timeEstimate: "1 hour/week" },
      { title: "Apply to junior developer positions", description: "Tailor resume, practice interviews", category: "work", priority: "high" as const, timeEstimate: "4 weeks" },
    ]
  },
  {
    activity: {
      title: "Home Renovation Project",
      description: "Kitchen remodel: contractors, materials, permits, and budget tracking",
      category: "personal" as const,
      planSummary: "Step-by-step kitchen renovation with contractor management and budget control",
      isPublic: true,
      shareTitle: "Home Renovation Project",
      backdrop: "beautiful_modern_hom_0f24a3e6.jpg",
      tags: ["home", "renovation", "remodel", "diy", "kitchen"],
      viewCount: 2100,
      likeCount: 2100,
      trendingScore: 4200,
      featuredInCommunity: true,
      creatorName: "Lisa Park",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Get 3 contractor quotes", description: "Licensed, insured, with references", category: "personal", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Apply for renovation permits", description: "Submit plans to city planning dept", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Order cabinets and countertops", description: "Measure precisely, order 8-10 weeks ahead", category: "personal", priority: "high" as const, timeEstimate: "4 hours" },
      { title: "Select appliances and fixtures", description: "Refrigerator, stove, sink, lighting", category: "personal", priority: "medium" as const, timeEstimate: "3 hours" },
      { title: "Schedule inspections post-renovation", description: "Electrical, plumbing, final walkthrough", category: "personal", priority: "medium" as const, timeEstimate: "1 hour" },
    ]
  },
  {
    activity: {
      title: "Master Productivity System",
      description: "Daily routines, time blocking, and focus techniques for peak performance",
      category: "work" as const,
      planSummary: "Evidence-based productivity framework combining time management and deep work principles",
      isPublic: true,
      shareTitle: "Master Productivity System",
      backdrop: "organized_productivi_df70e725.jpg",
      tags: ["productivity", "time-management", "focus", "routine", "work"],
      viewCount: 890,
      likeCount: 890,
      trendingScore: 1780,
      featuredInCommunity: false,
      creatorName: "David Lee",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Implement morning routine (5:30 AM start)", description: "Exercise, meditation, journaling", category: "work", priority: "high" as const, timeEstimate: "90 min" },
      { title: "Time-block calendar for deep work", description: "4-hour blocks for focused tasks", category: "work", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Use Pomodoro technique (25 min focus)", description: "Work in focused sprints with breaks", category: "work", priority: "high" as const, timeEstimate: "25 min" },
      { title: "Weekly review and planning session", description: "Reflect on wins, plan next week", category: "work", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Eliminate digital distractions", description: "Block social media during work hours", category: "work", priority: "medium" as const, timeEstimate: "15 min" },
    ]
  }
];
