import type { InsertActivity, InsertTask } from "@shared/schema";

// Demo community plans with high-quality stock images
export const demoCommunityPlans = [
  {
    activity: {
      title: "Weekend Trip to Paris",
      description: "Complete 3-day Paris itinerary with sights, dining, and Eiffel Tower visit",
      category: "travel" as const,
      planSummary: "Romantic 3-day Paris escape with iconic landmarks, French cuisine, and evening river cruise",
      isPublic: true,
      shareTitle: "Weekend Trip to Paris",
      backdrop: "/community-backdrops/romantic_paris_citys_dfc7c798.jpg",
      tags: ["travel", "paris", "europe", "weekend", "romantic"],
      viewCount: 2400,
      likeCount: 2400,
      trendingScore: 4800,
      featuredInCommunity: true,
      creatorName: "Sarah Chen",
      creatorAvatar: null,
      status: "completed" as const,
      budget: 350000,
      budgetBreakdown: [
        { category: "Flights", amount: 120000, notes: "Round-trip economy tickets" },
        { category: "Hotel", amount: 150000, notes: "3 nights boutique hotel in Le Marais" },
        { category: "Food", amount: 50000, notes: "Dining and cafes" },
        { category: "Activities", amount: 30000, notes: "Museum tickets, Eiffel Tower, river cruise" }
      ],
      budgetBuffer: 35000,
    },
    tasks: [
      { title: "Book hotel in Le Marais district", description: "Boutique hotel near Metro", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Visit Eiffel Tower at sunset", description: "Book tickets in advance to skip lines", category: "travel", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Explore Louvre Museum", description: "See Mona Lisa and Egyptian exhibits", category: "travel", priority: "high" as const, timeEstimate: "4 hours" },
      { title: "Seine River dinner cruise", description: "Evening cruise with French dinner", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Stroll through Montmartre", description: "Visit Sacré-Cœur and artist square", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "30-Day Fitness Challenge",
      description: "Daily workouts, meal prep, and progress tracking for complete transformation",
      category: "health" as const,
      planSummary: "Structured 30-day fitness program with workouts, nutrition plan, and accountability tracking",
      isPublic: true,
      shareTitle: "30-Day Fitness Challenge",
      backdrop: "/community-backdrops/fitness_workout_gym__2325ee98.jpg",
      tags: ["fitness", "health", "workout", "challenge", "30days"],
      viewCount: 1800,
      likeCount: 1800,
      trendingScore: 3600,
      featuredInCommunity: true,
      creatorName: "Mike Johnson",
      creatorAvatar: null,
      status: "active" as const,
      budget: 20000,
      budgetBreakdown: [
        { category: "Gym membership", amount: 10000, notes: "30-day gym pass" },
        { category: "Meal prep containers", amount: 3000, notes: "Reusable food storage set" },
        { category: "Resistance bands", amount: 4000, notes: "Set of 5 resistance levels" },
        { category: "Fitness tracker", amount: 3000, notes: "Basic heart rate monitor" }
      ],
      budgetBuffer: 2000,
    },
    tasks: [
      { title: "Week 1: Build foundation with bodyweight exercises", description: "Push-ups, squats, planks", category: "health", priority: "high" as const, timeEstimate: "45 min" },
      { title: "Meal prep healthy breakfast options", description: "Overnight oats, egg muffins, smoothie packs", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Week 2: Add resistance training", description: "Dumbbells and resistance bands", category: "health", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Track daily water intake (64oz)", description: "Use water tracking app", category: "health", priority: "medium" as const, timeEstimate: "5 min" },
      { title: "Weekly progress photos and measurements", description: "Track body composition changes", category: "health", priority: "medium" as const, timeEstimate: "10 min" },
    ]
  },
  {
    activity: {
      title: "Daily Meditation Practice",
      description: "30-day mindfulness program to reduce stress and improve mental clarity",
      category: "health" as const,
      planSummary: "Progressive meditation guide from 5-minute sessions to 20-minute daily practice with breath work",
      isPublic: true,
      shareTitle: "Daily Meditation Practice",
      backdrop: "/community-backdrops/person_meditating_pe_43f13693.jpg",
      tags: ["meditation", "mindfulness", "mental-health", "wellness", "stress-relief"],
      viewCount: 1650,
      likeCount: 1650,
      trendingScore: 3300,
      featuredInCommunity: true,
      creatorName: "Maya Patel",
      creatorAvatar: null,
      status: "active" as const,
      budget: 0,
      budgetBreakdown: [
        { category: "App subscription", amount: 0, notes: "Free apps (Insight Timer, UCLA Mindful App)" },
        { category: "Equipment", amount: 0, notes: "No special equipment needed - just a quiet space" }
      ],
      budgetBuffer: 0,
    },
    tasks: [
      { title: "Week 1: Start with 5-minute guided sessions", description: "Use Headspace or Calm app for beginner meditations", category: "health", priority: "high" as const, timeEstimate: "5 min/day" },
      { title: "Learn basic breathing techniques", description: "Box breathing (4-4-4-4) and 4-7-8 breath for relaxation", category: "health", priority: "high" as const, timeEstimate: "10 min" },
      { title: "Week 2: Increase to 10-minute sessions", description: "Morning meditation before coffee/breakfast", category: "health", priority: "high" as const, timeEstimate: "10 min/day" },
      { title: "Practice body scan meditation", description: "Release tension from head to toe systematically", category: "health", priority: "high" as const, timeEstimate: "15 min" },
      { title: "Week 3: Add evening gratitude practice", description: "Journal 3 things you're grateful for before bed", category: "health", priority: "medium" as const, timeEstimate: "5 min/day" },
      { title: "Week 4: Build to 20-minute daily practice", description: "Morning and evening sessions for consistency", category: "health", priority: "high" as const, timeEstimate: "20 min/day" },
      { title: "Join local meditation group or sangha", description: "Community practice for accountability and support", category: "health", priority: "medium" as const, timeEstimate: "1 hour/week" },
    ]
  },
  {
    activity: {
      title: "Wedding Planning Checklist",
      description: "12-month wedding plan with venue, vendors, guests, and timeline",
      category: "personal" as const,
      planSummary: "Complete wedding planning guide covering venue booking, vendor selection, and timeline management",
      isPublic: true,
      shareTitle: "Wedding Planning Checklist",
      backdrop: "/community-backdrops/elegant_wedding_cere_9aa2c585.jpg",
      tags: ["wedding", "planning", "events", "checklist", "celebration"],
      viewCount: 3200,
      likeCount: 3200,
      trendingScore: 6400,
      featuredInCommunity: true,
      creatorName: "Emma Davis",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 3500000,
      budgetBreakdown: [
        { category: "Venue & catering", amount: 1800000, notes: "150 guests, full dinner service" },
        { category: "Photography & videography", amount: 500000, notes: "Full-day coverage, albums" },
        { category: "Wedding dress & alterations", amount: 300000, notes: "Designer gown with fittings" },
        { category: "Flowers & decorations", amount: 250000, notes: "Bouquets, centerpieces, ceremony decor" },
        { category: "Music & entertainment", amount: 200000, notes: "DJ and live band for ceremony" },
        { category: "Invitations & stationery", amount: 150000, notes: "Save-the-dates, invites, programs" },
        { category: "Cake & desserts", amount: 100000, notes: "3-tier cake and dessert bar" },
        { category: "Transportation", amount: 50000, notes: "Limo service for wedding party" },
        { category: "Misc & contingency", amount: 150000, notes: "Hair, makeup, favors, tips" }
      ],
      budgetBuffer: 350000,
    },
    tasks: [
      { title: "Set wedding budget and priorities", description: "Allocate funds across venue, catering, photography", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Book wedding venue (12 months out)", description: "Visit 3-5 venues, secure date", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Hire photographer and videographer", description: "Review portfolios, book 9-12 months ahead", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Finalize guest list and send save-the-dates", description: "Confirm addresses, design and mail STDs", category: "personal", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Schedule dress fittings and alterations", description: "Order dress 8-10 months out, fittings begin", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Career Switch to Tech",
      description: "6-month plan: coding bootcamp, portfolio projects, and job applications",
      category: "career" as const,
      planSummary: "Comprehensive career transition roadmap from non-tech to software development role",
      isPublic: true,
      shareTitle: "Career Switch to Tech",
      backdrop: "/community-backdrops/professional_develop_960cd8cf.jpg",
      tags: ["career", "tech", "coding", "bootcamp", "transition"],
      viewCount: 1500,
      likeCount: 1500,
      trendingScore: 3000,
      featuredInCommunity: true,
      creatorName: "Alex Kim",
      creatorAvatar: null,
      status: "active" as const,
      budget: 1200000,
      budgetBreakdown: [
        { category: "Coding bootcamp tuition", amount: 1000000, notes: "12-week immersive program" },
        { category: "Laptop & equipment", amount: 120000, notes: "MacBook for development work" },
        { category: "Books & learning resources", amount: 30000, notes: "Technical books and courses" },
        { category: "Certification exams", amount: 20000, notes: "AWS or similar certifications" },
        { category: "Networking events", amount: 30000, notes: "Meetups, conferences, memberships" }
      ],
      budgetBuffer: 120000,
    },
    tasks: [
      { title: "Complete HTML/CSS/JavaScript fundamentals", description: "FreeCodeCamp or Codecademy - 3 months", category: "work", priority: "high" as const, timeEstimate: "80 hours" },
      { title: "Enroll in coding bootcamp or online program", description: "Research Flatiron, General Assembly, or The Odin Project", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Build personal portfolio website", description: "Showcase your skills and projects", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Complete 3 full-stack projects", description: "E-commerce site, social app, API integration", category: "work", priority: "high" as const, timeEstimate: "3 months" },
      { title: "Contribute to open source projects", description: "Build GitHub profile with meaningful contributions", category: "work", priority: "medium" as const, timeEstimate: "1 month" },
      { title: "Network and attend tech meetups", description: "Join local dev communities, LinkedIn connections", category: "work", priority: "medium" as const, timeEstimate: "2 hours/week" },
      { title: "Apply to 50+ junior developer positions", description: "Tailor resume/cover letter, practice LeetCode", category: "work", priority: "high" as const, timeEstimate: "6 weeks" },
    ]
  },
  {
    activity: {
      title: "Home Renovation Project",
      description: "Complete kitchen remodel timeline with contractor coordination and budget",
      category: "home" as const,
      planSummary: "Step-by-step kitchen renovation with contractor management and budget control",
      isPublic: true,
      shareTitle: "Home Renovation Project",
      backdrop: "/community-backdrops/modern_kitchen_renov_a5563863.jpg",
      tags: ["home", "renovation", "remodel", "diy", "kitchen"],
      viewCount: 2100,
      likeCount: 2100,
      trendingScore: 4200,
      featuredInCommunity: true,
      creatorName: "John Smith",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 4500000,
      budgetBreakdown: [
        { category: "Custom cabinets", amount: 1500000, notes: "Soft-close drawers, premium finishes" },
        { category: "Quartz countertops", amount: 800000, notes: "Full kitchen perimeter with island" },
        { category: "Appliances", amount: 600000, notes: "Stainless steel fridge, range, dishwasher, microwave" },
        { category: "Labor & installation", amount: 1000000, notes: "Licensed contractors, electrician, plumber" },
        { category: "Flooring", amount: 300000, notes: "Luxury vinyl or tile flooring" },
        { category: "Lighting & fixtures", amount: 150000, notes: "Recessed lights, pendant over island" },
        { category: "Permits & inspections", amount: 50000, notes: "City permits and final inspections" },
        { category: "Misc & contingency", amount: 100000, notes: "Hardware, backsplash, touch-ups" }
      ],
      budgetBuffer: 450000,
    },
    tasks: [
      { title: "Set renovation budget and priorities", description: "Determine must-haves vs nice-to-haves, allocate $30-60k", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Get 3-5 contractor quotes", description: "Licensed, insured contractors with references", category: "personal", priority: "high" as const, timeEstimate: "3 weeks" },
      { title: "Apply for building permits", description: "Submit renovation plans to city planning department", category: "personal", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Order custom cabinets and countertops", description: "Granite or quartz counters, soft-close cabinets - order 8-10 weeks ahead", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Select and purchase appliances", description: "Stainless steel refrigerator, range, dishwasher, microwave", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Demolition and rough-in work", description: "Remove old cabinets, update electrical/plumbing rough-ins", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Final installation and inspection", description: "Install cabinets, counters, appliances, lighting - final inspection", category: "personal", priority: "high" as const, timeEstimate: "2 weeks" },
    ]
  },
  {
    activity: {
      title: "Master Productivity System",
      description: "Daily routines, time blocking, and focus techniques for peak performance",
      category: "work" as const,
      planSummary: "Evidence-based productivity framework combining time management and deep work principles",
      isPublic: true,
      shareTitle: "Master Productivity System",
      backdrop: "/community-backdrops/organized_productivi_df70e725.jpg",
      tags: ["productivity", "time-management", "focus", "routine", "work"],
      viewCount: 890,
      likeCount: 890,
      trendingScore: 1780,
      featuredInCommunity: false,
      creatorName: "David Lee",
      creatorAvatar: null,
      status: "active" as const,
      budget: 0,
      budgetBreakdown: [
        { category: "Productivity tools", amount: 0, notes: "Free tools (Google Calendar, Todoist free tier)" },
        { category: "Resources", amount: 0, notes: "Free online guides and templates" }
      ],
      budgetBuffer: 0,
    },
    tasks: [
      { title: "Implement morning routine (5:30 AM start)", description: "Exercise, meditation, journaling", category: "work", priority: "high" as const, timeEstimate: "90 min" },
      { title: "Time-block calendar for deep work", description: "4-hour blocks for focused tasks", category: "work", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Use Pomodoro technique (25 min focus)", description: "Work in focused sprints with breaks", category: "work", priority: "high" as const, timeEstimate: "25 min" },
      { title: "Weekly review and planning session", description: "Reflect on wins, plan next week", category: "work", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Eliminate digital distractions", description: "Block social media during work hours", category: "work", priority: "medium" as const, timeEstimate: "15 min" },
    ]
  },
  {
    activity: {
      title: "Digital Nomad Guide to Bali",
      description: "Remote work paradise: visa, coworking spaces, best neighborhoods, and scooter rentals",
      category: "travel" as const,
      planSummary: "Complete guide for remote workers relocating to Bali with workspace, visa, and living tips",
      isPublic: true,
      shareTitle: "Digital Nomad Guide to Bali",
      backdrop: "/community-backdrops/bali_indonesia_tropi_95575be5.jpg",
      tags: ["travel", "bali", "digital-nomad", "remote-work", "asia"],
      viewCount: 1950,
      likeCount: 1650,
      trendingScore: 3600,
      featuredInCommunity: true,
      creatorName: "Jordan Rivera",
      creatorAvatar: null,
      status: "active" as const,
      budget: 300000,
      budgetBreakdown: [
        { category: "Visa & permits", amount: 50000, notes: "B211A visa processing fees" },
        { category: "Coworking membership", amount: 80000, notes: "2-month Dojo Bali membership" },
        { category: "Scooter rental", amount: 40000, notes: "2-month motorbike rental" },
        { category: "Accommodation deposit", amount: 100000, notes: "First month + security deposit" },
        { category: "SIM card & internet", amount: 30000, notes: "Local SIM with data package" }
      ],
      budgetBuffer: 30000,
    },
    tasks: [
      { title: "Apply for B211A visa (60 days)", description: "Required documents and embassy appointment", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Book Airbnb in Canggu or Ubud", description: "Near coworking spaces with fast WiFi", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Join Dojo Bali or Hubud coworking", description: "Monthly membership for reliable internet", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Rent scooter and get international license", description: "Essential for island mobility", category: "travel", priority: "medium" as const, timeEstimate: "3 hours" },
      { title: "Set up Indonesian bank account", description: "For local payments and withdrawals", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Marathon Training: 16-Week Plan",
      description: "First-time marathoner? Build endurance from 5K to 26.2 miles with injury prevention",
      category: "health" as const,
      planSummary: "Structured 16-week training program with progressive mileage, nutrition, and recovery strategies",
      isPublic: true,
      shareTitle: "Marathon Training: 16-Week Plan",
      backdrop: "/community-backdrops/runner_jogging_on_tr_9a63ddad.jpg",
      tags: ["fitness", "running", "marathon", "training", "endurance"],
      viewCount: 2850,
      likeCount: 2400,
      trendingScore: 5250,
      featuredInCommunity: true,
      creatorName: "Rachel Martinez",
      creatorAvatar: null,
      status: "active" as const,
      budget: 25000,
      budgetBreakdown: [
        { category: "Running shoes", amount: 15000, notes: "Professional fitting at specialty store" },
        { category: "Race registration", amount: 5000, notes: "Marathon entry fee" },
        { category: "Running gear", amount: 3000, notes: "Moisture-wicking shirts, shorts" },
        { category: "Nutrition supplies", amount: 2000, notes: "Energy gels, electrolyte drinks" }
      ],
      budgetBuffer: 2500,
    },
    tasks: [
      { title: "Weeks 1-4: Build base (20-30 miles/week)", description: "Easy pace with one long run", category: "health", priority: "high" as const, timeEstimate: "6 hours/week" },
      { title: "Get fitted for proper running shoes", description: "Visit running specialty store for gait analysis", category: "health", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Weeks 5-8: Add tempo runs (35-40 miles/week)", description: "Increase pace on mid-week runs", category: "health", priority: "high" as const, timeEstimate: "7 hours/week" },
      { title: "Practice race-day nutrition strategy", description: "Test gels, hydration during long runs", category: "health", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Weeks 12-16: Taper and race prep", description: "Reduce mileage, rest, carb load", category: "health", priority: "medium" as const, timeEstimate: "4 hours/week" },
    ]
  },
  {
    activity: {
      title: "Tokyo Adventure: 7-Day Itinerary",
      description: "Shibuya crossing, Mt. Fuji day trip, ramen tours, and hidden temples",
      category: "travel" as const,
      planSummary: "Week-long Tokyo exploration blending modern culture, traditional sites, and culinary experiences",
      isPublic: true,
      shareTitle: "Tokyo Adventure: 7-Day Itinerary",
      backdrop: "/community-backdrops/tokyo_japan_travel_d_8a196170.jpg",
      tags: ["travel", "tokyo", "japan", "culture", "food"],
      viewCount: 3400,
      likeCount: 2900,
      trendingScore: 6300,
      featuredInCommunity: true,
      creatorName: "Kenji Tanaka",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 450000,
      budgetBreakdown: [
        { category: "Flights", amount: 180000, notes: "Round-trip from US to Tokyo" },
        { category: "Hotel", amount: 140000, notes: "7 nights mid-range hotel in Shinjuku" },
        { category: "JR Rail Pass", amount: 30000, notes: "7-day unlimited train travel" },
        { category: "Food & dining", amount: 60000, notes: "Ramen, sushi, street food, restaurants" },
        { category: "Activities", amount: 40000, notes: "TeamLab, Mt. Fuji tour, temple visits" }
      ],
      budgetBuffer: 45000,
    },
    tasks: [
      { title: "Get JR Rail Pass (7-day)", description: "Order online 2 weeks before trip", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Day 1: Shibuya & Harajuku exploration", description: "Scramble crossing, Meiji Shrine, Takeshita Street", category: "travel", priority: "high" as const, timeEstimate: "8 hours" },
      { title: "Day 3: Mt. Fuji day trip from Shinjuku", description: "Early morning bus to 5th station", category: "travel", priority: "high" as const, timeEstimate: "12 hours" },
      { title: "Reserve TeamLab Borderless tickets", description: "Digital art museum, book weeks ahead", category: "travel", priority: "medium" as const, timeEstimate: "30 min" },
      { title: "Day 5: Tsukiji Market breakfast & Senso-ji Temple", description: "Fresh sushi and traditional shopping", category: "travel", priority: "medium" as const, timeEstimate: "6 hours" },
    ]
  },
  {
    activity: {
      title: "Launch Your Side Hustle",
      description: "Validate idea, build MVP, get first 10 customers in 90 days",
      category: "work" as const,
      planSummary: "Practical startup framework from idea validation to revenue generation in 3 months",
      isPublic: true,
      shareTitle: "Launch Your Side Hustle",
      backdrop: "/community-backdrops/modern_workspace_des_9f6c2608.jpg",
      tags: ["entrepreneurship", "startup", "side-hustle", "business", "revenue"],
      viewCount: 1750,
      likeCount: 1500,
      trendingScore: 3250,
      featuredInCommunity: true,
      creatorName: "Priya Sharma",
      creatorAvatar: null,
      status: "active" as const,
      budget: 30000,
      budgetBreakdown: [
        { category: "Landing page builder", amount: 10000, notes: "Webflow or Carrd annual subscription" },
        { category: "Paid ads testing", amount: 20000, notes: "Facebook/Google Ads budget for validation" }
      ],
      budgetBuffer: 3000,
    },
    tasks: [
      { title: "Validate idea with 20 customer interviews", description: "Talk to target customers about pain points", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Build landing page with email capture", description: "Use Carrd or Webflow, test messaging", category: "work", priority: "high" as const, timeEstimate: "8 hours" },
      { title: "Create MVP in 2-3 weeks", description: "Minimum viable product, not perfect", category: "work", priority: "high" as const, timeEstimate: "40 hours" },
      { title: "Run small paid ads campaign ($200 budget)", description: "Facebook or Google Ads to test demand", category: "work", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Reach out to first 100 potential customers", description: "Email, LinkedIn, Twitter DMs", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
    ]
  },
  {
    activity: {
      title: "Master Public Speaking",
      description: "Overcome stage fright, craft compelling talks, and deliver with confidence",
      category: "work" as const,
      planSummary: "8-week public speaking mastery program with Toastmasters, speech writing, and TEDx prep",
      isPublic: true,
      shareTitle: "Master Public Speaking",
      backdrop: "/community-backdrops/business_presentatio_aee687af.jpg",
      tags: ["public-speaking", "communication", "career", "confidence", "presentation"],
      viewCount: 1320,
      likeCount: 1100,
      trendingScore: 2420,
      featuredInCommunity: false,
      creatorName: "Marcus Thompson",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 20000,
      budgetBreakdown: [
        { category: "Toastmasters membership", amount: 10000, notes: "6-month club dues" },
        { category: "Public speaking course", amount: 7000, notes: "Online masterclass or workshop" },
        { category: "Books & resources", amount: 3000, notes: "Speaking guides and TED talk analysis" }
      ],
      budgetBuffer: 2000,
    },
    tasks: [
      { title: "Join local Toastmasters club", description: "Attend meetings twice monthly for practice", category: "work", priority: "high" as const, timeEstimate: "2 hours/meeting" },
      { title: "Record yourself giving 3 practice speeches", description: "Review body language and vocal patterns", category: "work", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Write and memorize signature talk (10 min)", description: "Use storytelling framework", category: "work", priority: "high" as const, timeEstimate: "12 hours" },
      { title: "Practice power poses before speaking", description: "Amy Cuddy's confidence technique", category: "work", priority: "medium" as const, timeEstimate: "5 min" },
      { title: "Apply to speak at local meetups or conferences", description: "Start small, build experience", category: "work", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "NYC Holiday Magic: Christmas Week",
      description: "Rockefeller tree, ice skating, Broadway shows, and holiday markets",
      category: "travel" as const,
      planSummary: "Festive New York City experience with iconic holiday traditions and winter activities",
      isPublic: true,
      shareTitle: "NYC Holiday Magic: Christmas Week",
      backdrop: "/community-backdrops/new_york_city_times__e09e766b.jpg",
      tags: ["travel", "nyc", "christmas", "holiday", "winter"],
      viewCount: 2650,
      likeCount: 2200,
      trendingScore: 4850,
      featuredInCommunity: true,
      creatorName: "Amanda Collins",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 380000,
      budgetBreakdown: [
        { category: "Hotel", amount: 180000, notes: "5 nights in Midtown during holidays" },
        { category: "Broadway tickets", amount: 100000, notes: "Premium seats for 2 shows" },
        { category: "Food & dining", amount: 60000, notes: "Holiday dinners and restaurants" },
        { category: "Activities", amount: 40000, notes: "Ice skating, museums, attractions" }
      ],
      budgetBuffer: 38000,
    },
    tasks: [
      { title: "Book Broadway show tickets (Hamilton or Wicked)", description: "Reserve 2-3 months ahead for holiday dates", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Visit Rockefeller Center Christmas Tree", description: "See tree lighting or visit early morning", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Ice skate at Bryant Park (free admission)", description: "Bring warm clothes, rent skates on-site", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Explore holiday markets (Union Square, Columbus Circle)", description: "Shop for gifts and hot chocolate", category: "travel", priority: "medium" as const, timeEstimate: "3 hours" },
      { title: "Walk through Dyker Heights Christmas lights (Brooklyn)", description: "Over-the-top neighborhood decorations", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Mindfulness & Meditation Practice",
      description: "21-day habit builder with guided sessions, breathwork, and journaling",
      category: "health" as const,
      planSummary: "Structured meditation program for beginners to establish daily mindfulness routine",
      isPublic: true,
      shareTitle: "Mindfulness & Meditation Practice",
      backdrop: "/community-backdrops/yoga_studio_peaceful_84f9a366.jpg",
      tags: ["mindfulness", "meditation", "mental-health", "wellness", "habit"],
      viewCount: 1580,
      likeCount: 1320,
      trendingScore: 2900,
      featuredInCommunity: true,
      creatorName: "Elena Rodriguez",
      creatorAvatar: null,
      status: "active" as const,
      budget: 0,
      budgetBreakdown: [
        { category: "App subscription", amount: 0, notes: "Free apps (Headspace basic, Calm)" },
        { category: "Materials", amount: 0, notes: "Journal and cushion (optional, use what you have)" }
      ],
      budgetBuffer: 0,
    },
    tasks: [
      { title: "Days 1-7: 5-minute morning meditation", description: "Use Headspace or Calm app", category: "health", priority: "high" as const, timeEstimate: "5 min/day" },
      { title: "Set up meditation space at home", description: "Quiet corner with cushion, minimal distractions", category: "health", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Days 8-14: Add breathwork (box breathing)", description: "4-4-4-4 pattern for stress relief", category: "health", priority: "high" as const, timeEstimate: "10 min/day" },
      { title: "Keep gratitude journal (evening)", description: "Write 3 things daily", category: "health", priority: "medium" as const, timeEstimate: "5 min/day" },
      { title: "Days 15-21: Extend to 15-minute sessions", description: "Deepen practice, notice improvements", category: "health", priority: "medium" as const, timeEstimate: "15 min/day" },
    ]
  },
  {
    activity: {
      title: "Iceland Northern Lights Expedition",
      description: "Chase aurora borealis, explore ice caves, and relax in Blue Lagoon",
      category: "travel" as const,
      planSummary: "5-day Iceland adventure focusing on Northern Lights photography and natural wonders",
      isPublic: true,
      shareTitle: "Iceland Northern Lights Expedition",
      backdrop: "/community-backdrops/iceland_northern_lig_9fbbf14d.jpg",
      tags: ["travel", "iceland", "northern-lights", "adventure", "photography"],
      viewCount: 2190,
      likeCount: 1850,
      trendingScore: 4040,
      featuredInCommunity: true,
      creatorName: "Stefan Olafsson",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 420000,
      budgetBreakdown: [
        { category: "Flights", amount: 150000, notes: "Round-trip to Reykjavik" },
        { category: "4WD car rental", amount: 100000, notes: "5 days winter rental with insurance" },
        { category: "Accommodation", amount: 80000, notes: "4 nights in guesthouses" },
        { category: "Blue Lagoon", amount: 40000, notes: "Premium entry with towel rental" },
        { category: "Ice cave tour", amount: 30000, notes: "Guided glacier tour" },
        { category: "Food & supplies", amount: 20000, notes: "Groceries and gas stations" }
      ],
      budgetBuffer: 42000,
    },
    tasks: [
      { title: "Book trip between September-March", description: "Peak aurora season with longer nights", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Rent 4WD vehicle for Ring Road drive", description: "Essential for winter road conditions", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Reserve Blue Lagoon premium entry", description: "Book weeks ahead, go at sunset", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Download Aurora forecast app", description: "Track KP index and cloud cover", category: "travel", priority: "medium" as const, timeEstimate: "15 min" },
      { title: "Join guided ice cave tour in Vatnajökull", description: "Safe exploration with expert guides", category: "travel", priority: "medium" as const, timeEstimate: "4 hours" },
    ]
  },
  {
    activity: {
      title: "Cycling Century Ride: 100-Mile Challenge",
      description: "12-week training plan from 20 miles to 100-mile century ride",
      category: "health" as const,
      planSummary: "Progressive cycling program building endurance for first 100-mile ride with nutrition tips",
      isPublic: true,
      shareTitle: "Cycling Century Ride: 100-Mile Challenge",
      backdrop: "/community-backdrops/cyclist_riding_bike__9ae17ca2.jpg",
      tags: ["cycling", "fitness", "endurance", "challenge", "training"],
      viewCount: 1240,
      likeCount: 1050,
      trendingScore: 2290,
      featuredInCommunity: false,
      creatorName: "Tyler Chen",
      creatorAvatar: null,
      status: "active" as const,
      budget: 30000,
      budgetBreakdown: [
        { category: "Bike fit session", amount: 15000, notes: "Professional fitting service" },
        { category: "Cycling gear", amount: 8000, notes: "Padded shorts, jerseys, gloves" },
        { category: "Nutrition supplies", amount: 4000, notes: "Energy bars, gels, electrolytes" },
        { category: "Century ride entry", amount: 3000, notes: "Event registration fee" }
      ],
      budgetBuffer: 3000,
    },
    tasks: [
      { title: "Weeks 1-4: Build base (50-70 miles/week)", description: "3-4 rides with progressive distance", category: "health", priority: "high" as const, timeEstimate: "6 hours/week" },
      { title: "Get professional bike fit", description: "Prevent injury, improve efficiency", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Weeks 5-8: Add interval training", description: "Hill repeats and tempo rides", category: "health", priority: "high" as const, timeEstimate: "7 hours/week" },
      { title: "Practice nutrition strategy on long rides", description: "Test energy bars, electrolytes", category: "health", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Weeks 10-12: Peak with 80-mile ride, then taper", description: "Final long ride 2 weeks before century", category: "health", priority: "medium" as const, timeEstimate: "8 hours" },
    ]
  },
  {
    activity: {
      title: "Learn Spanish in 90 Days",
      description: "Daily practice schedule, vocabulary building, and conversation practice",
      category: "learning" as const,
      planSummary: "Immersive Spanish learning program with daily practice and real conversation partners",
      isPublic: true,
      shareTitle: "Learn Spanish in 90 Days",
      backdrop: "/community-backdrops/spanish_language_lea_269b1aa7.jpg",
      tags: ["learning", "spanish", "language", "education", "practice"],
      viewCount: 1200,
      likeCount: 1200,
      trendingScore: 2400,
      featuredInCommunity: true,
      creatorName: "Lisa Garcia",
      creatorAvatar: null,
      status: "active" as const,
      budget: 48000,
      budgetBreakdown: [
        { category: "italki tutoring", amount: 36000, notes: "12 sessions @ $30 each" },
        { category: "Duolingo Plus", amount: 7000, notes: "3-month subscription" },
        { category: "Spanish books", amount: 5000, notes: "Textbooks and readers" }
      ],
      budgetBuffer: 4800,
    },
    tasks: [
      { title: "Complete Duolingo Spanish course (30 min/day)", description: "Build foundation with vocabulary and grammar basics", category: "personal", priority: "high" as const, timeEstimate: "30 min/day" },
      { title: "Practice with italki tutor 3x per week", description: "One-on-one conversation with native Spanish speakers", category: "personal", priority: "high" as const, timeEstimate: "1 hour/session" },
      { title: "Watch Spanish shows with subtitles", description: "Start with English subs, then Spanish only - Netflix/HBO", category: "personal", priority: "high" as const, timeEstimate: "30 min/day" },
      { title: "Learn 20 new words daily with flashcards", description: "Use Anki spaced repetition system for retention", category: "personal", priority: "high" as const, timeEstimate: "15 min/day" },
      { title: "Join local Spanish conversation meetup", description: "Practice speaking in relaxed group setting weekly", category: "personal", priority: "medium" as const, timeEstimate: "2 hours/week" },
      { title: "Read Spanish children's books and news", description: "Start simple, progress to El País newspaper", category: "personal", priority: "medium" as const, timeEstimate: "20 min/day" },
      { title: "Travel to Spanish-speaking country for immersion", description: "2-week trip to practice real-world conversations", category: "personal", priority: "medium" as const, timeEstimate: "2 weeks" },
    ]
  },
  {
    activity: {
      title: "Strength Training for Beginners",
      description: "8-week progressive overload program with compound movements",
      category: "health" as const,
      planSummary: "Science-based strength program teaching squat, deadlift, bench press, and overhead press fundamentals",
      isPublic: true,
      shareTitle: "Strength Training for Beginners",
      backdrop: "/community-backdrops/modern_gym_workout_w_99dc5406.jpg",
      tags: ["fitness", "strength-training", "gym", "muscle", "beginner"],
      viewCount: 2050,
      likeCount: 1750,
      trendingScore: 3800,
      featuredInCommunity: true,
      creatorName: "Chris Anderson",
      creatorAvatar: null,
      status: "active" as const,
      budget: 15000,
      budgetBreakdown: [
        { category: "Gym membership", amount: 10000, notes: "2-month membership" },
        { category: "Workout gear", amount: 3000, notes: "Lifting shoes and belt" },
        { category: "Protein powder", amount: 2000, notes: "Whey protein supplement" }
      ],
      budgetBuffer: 1500,
    },
    tasks: [
      { title: "Learn proper form for big 4 lifts", description: "Squat, deadlift, bench, overhead press - watch videos", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Start with empty barbell (45 lbs)", description: "Master form before adding weight", category: "health", priority: "high" as const, timeEstimate: "3 sessions" },
      { title: "Follow 3x/week full-body program", description: "Monday/Wednesday/Friday schedule", category: "health", priority: "high" as const, timeEstimate: "1 hour/session" },
      { title: "Track lifts in fitness app", description: "Progressive overload: add 5 lbs weekly", category: "health", priority: "medium" as const, timeEstimate: "10 min" },
      { title: "Eat in caloric surplus (300-500 cals)", description: "Support muscle growth with protein", category: "health", priority: "medium" as const, timeEstimate: "daily" },
    ]
  },
  {
    activity: {
      title: "Professional Networking Strategy",
      description: "Build genuine relationships, attend industry events, and grow LinkedIn presence",
      category: "work" as const,
      planSummary: "90-day networking plan to expand professional connections and unlock career opportunities",
      isPublic: true,
      shareTitle: "Professional Networking Strategy",
      backdrop: "/community-backdrops/professional_network_48ccc448.jpg",
      tags: ["networking", "career", "linkedin", "professional-development", "relationships"],
      viewCount: 1450,
      likeCount: 1200,
      trendingScore: 2650,
      featuredInCommunity: true,
      creatorName: "Jennifer Wong",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 10000,
      budgetBreakdown: [
        { category: "Professional headshot", amount: 5000, notes: "LinkedIn profile photo" },
        { category: "Event tickets", amount: 3000, notes: "Industry conferences and meetups" },
        { category: "Coffee meetings", amount: 2000, notes: "Informational interviews" }
      ],
      budgetBuffer: 1000,
    },
    tasks: [
      { title: "Optimize LinkedIn profile with keywords", description: "Professional photo, compelling headline", category: "work", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Attend 2 industry meetups monthly", description: "Find events on Meetup.com or Eventbrite", category: "work", priority: "high" as const, timeEstimate: "4 hours/month" },
      { title: "Send 5 personalized connection requests weekly", description: "Reference shared interests or mutual connections", category: "work", priority: "high" as const, timeEstimate: "30 min/week" },
      { title: "Schedule 2 coffee chats monthly", description: "Informational interviews with industry pros", category: "work", priority: "medium" as const, timeEstimate: "2 hours/month" },
      { title: "Share valuable content on LinkedIn (2x/week)", description: "Industry insights, personal experiences", category: "work", priority: "medium" as const, timeEstimate: "30 min/week" },
    ]
  },
  {
    activity: {
      title: "Personal Reading Challenge: 52 Books",
      description: "One book per week with diverse genres, discussion groups, and reflection journal",
      category: "personal" as const,
      planSummary: "Year-long reading habit with curated book list, tracking system, and community engagement",
      isPublic: true,
      shareTitle: "Personal Reading Challenge: 52 Books",
      backdrop: "/community-backdrops/person_reading_book__bc916131.jpg",
      tags: ["reading", "books", "personal-growth", "learning", "habit"],
      viewCount: 1680,
      likeCount: 1400,
      trendingScore: 3080,
      featuredInCommunity: true,
      creatorName: "Olivia Brown",
      creatorAvatar: null,
      status: "active" as const,
      budget: 0,
      budgetBreakdown: [
        { category: "Books", amount: 0, notes: "Use library or free Libby app for ebooks/audiobooks" },
        { category: "Reading tracker", amount: 0, notes: "Free Goodreads account for progress tracking" }
      ],
      budgetBuffer: 0,
    },
    tasks: [
      { title: "Create reading list with genre variety", description: "Fiction, non-fiction, biography, self-help mix", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Set daily reading time (30 min before bed)", description: "Consistent habit, no phone", category: "personal", priority: "high" as const, timeEstimate: "30 min/day" },
      { title: "Join Goodreads and book club community", description: "Track progress, get recommendations", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Write reflection notes after each book", description: "Key takeaways, favorite quotes", category: "personal", priority: "medium" as const, timeEstimate: "20 min/book" },
      { title: "Visit library or use Libby app", description: "Free access to audiobooks and ebooks", category: "personal", priority: "medium" as const, timeEstimate: "1 hour" },
    ]
  },
  {
    activity: {
      title: "Epic Birthday Party: 30th Celebration",
      description: "Venue, theme, guest list, catering, entertainment, and surprise moments",
      category: "personal" as const,
      planSummary: "Complete party planning guide for milestone birthday with 50-80 guests",
      isPublic: true,
      shareTitle: "Epic Birthday Party: 30th Celebration",
      backdrop: "/community-backdrops/birthday_party_celeb_414d649e.jpg",
      tags: ["birthday", "party", "celebration", "event-planning", "milestone"],
      viewCount: 1890,
      likeCount: 1600,
      trendingScore: 3490,
      featuredInCommunity: true,
      creatorName: "Michael Torres",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 250000,
      budgetBreakdown: [
        { category: "Venue rental", amount: 80000, notes: "Private event space for 80 guests" },
        { category: "Catering", amount: 100000, notes: "Food and bar service" },
        { category: "DJ & entertainment", amount: 40000, notes: "Music and photo booth" },
        { category: "Decorations", amount: 20000, notes: "Theme decor and balloons" },
        { category: "Cake", amount: 10000, notes: "Custom birthday cake" }
      ],
      budgetBuffer: 25000,
    },
    tasks: [
      { title: "Book venue 2-3 months ahead", description: "Restaurant private room or event space", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Choose party theme (decade, tropical, casino)", description: "Coordinate decor and dress code", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Send digital invitations (Paperless Post)", description: "RSVP deadline 2 weeks before", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Arrange catering or food stations", description: "Consider dietary restrictions", category: "personal", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Plan surprise element or entertainment", description: "DJ, photo booth, or special performance", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Music Festival Survival Guide",
      description: "Packing list, camping setup, schedule planning, and festival hacks",
      category: "personal" as const,
      planSummary: "Complete preparation guide for multi-day music festival with camping tips and safety essentials",
      isPublic: true,
      shareTitle: "Music Festival Survival Guide",
      backdrop: "/community-backdrops/concert_music_festiv_18316657.jpg",
      tags: ["festival", "music", "camping", "travel", "events"],
      viewCount: 2340,
      likeCount: 1950,
      trendingScore: 4290,
      featuredInCommunity: true,
      creatorName: "Sophie Anderson",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 80000,
      budgetBreakdown: [
        { category: "Festival ticket", amount: 40000, notes: "3-day general admission pass" },
        { category: "Camping gear", amount: 20000, notes: "Tent, sleeping bag, camp chair" },
        { category: "Food & drinks", amount: 12000, notes: "Snacks and hydration supplies" },
        { category: "Transportation", amount: 8000, notes: "Gas and parking fees" }
      ],
      budgetBuffer: 8000,
    },
    tasks: [
      { title: "Pack festival essentials kit", description: "Tent, sleeping bag, portable charger, sunscreen", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Review lineup and create set schedule", description: "Prioritize must-see artists, plan conflicts", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Prepare hydration and food strategy", description: "Reusable water bottle, energy bars, cashless payment", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Set up camp in shaded area early", description: "Arrive Thursday to secure good spot", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Coordinate meeting spots with friends", description: "Cell service unreliable, plan meetup times/locations", category: "personal", priority: "medium" as const, timeEstimate: "30 min" },
    ]
  },
  {
    activity: {
      title: "Sunday NFL Game Day Experience",
      description: "Ultimate NFL game day with tailgate party, stadium experience, and safe transportation home",
      category: "personal" as const,
      planSummary: "Complete NFL game day experience with pre-game tailgate, stadium excitement, and responsible post-game celebration",
      isPublic: true,
      shareTitle: "Sunday NFL Game Day Experience",
      backdrop: "/community-backdrops/american_football_ga_70a5d33b.jpg",
      tags: ["nfl", "football", "gameday", "sports", "austin", "tailgate"],
      viewCount: 1890,
      likeCount: 1560,
      trendingScore: 3450,
      featuredInCommunity: true,
      creatorName: "Marcus Williams",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 120000,
      budgetBreakdown: [
        { category: "Game tickets", amount: 65000, notes: "2 tickets upper deck section" },
        { category: "Tailgate supplies", amount: 25000, notes: "Food, drinks, grill rentals, team gear" },
        { category: "Rideshare home", amount: 15000, notes: "Uber/Lyft for safe transportation" },
        { category: "Stadium food & merch", amount: 15000, notes: "Concessions and souvenirs" }
      ],
      budgetBuffer: 12000,
    },
    tasks: [
      { title: "Purchase game tickets 2-3 weeks in advance", description: "Check for early bird discounts on StubHub or NFL Ticket Exchange", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Organize tailgate crew and assign contributions", description: "Coordinate who brings grill, cooler, chairs, games, food", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Arrive at parking lot 3 hours before kickoff", description: "Secure prime tailgate spot near stadium entrance", category: "personal", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Set up tailgate station with grill and games", description: "Cornhole, ladder toss, music setup, team decorations", category: "personal", priority: "high" as const, timeEstimate: "45 min" },
      { title: "Prepare game day feast", description: "Wings, burgers, brats, nachos, and beverages", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Designate sober driver OR schedule rideshare", description: "Pre-book Uber/Lyft pickup 30 min after game ends", category: "personal", priority: "high" as const, timeEstimate: "15 min" },
      { title: "Enter stadium 45 minutes before kickoff", description: "Clear bag policy - bring essentials only", category: "personal", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Enjoy the game and capture memories", description: "Photos, videos, participate in stadium traditions", category: "personal", priority: "medium" as const, timeEstimate: "3.5 hours" },
      { title: "Wait 20-30 min post-game for traffic to clear", description: "Grab concessions, visit team store, avoid parking chaos", category: "personal", priority: "medium" as const, timeEstimate: "30 min" },
      { title: "Get home safely via rideshare or carpool", description: "Never drive after drinking - confirm pickup location with driver", category: "personal", priority: "high" as const, timeEstimate: "30 min" },
    ]
  },
  {
    activity: {
      title: "Sunday Funday in Austin",
      description: "Perfect Austin Sunday with brunch, outdoor activities, live music, and sunset drinks",
      category: "personal" as const,
      planSummary: "Quintessential Austin Sunday featuring bottomless brunch, Zilker Park hangout, South Congress shopping, and live music at a local venue",
      isPublic: true,
      shareTitle: "Sunday Funday in Austin",
      backdrop: "/community-backdrops/austin_texas_zilker__3b0e26dc.jpg",
      tags: ["austin", "sunday", "brunch", "music", "local", "weekend"],
      viewCount: 2100,
      likeCount: 1820,
      trendingScore: 3920,
      featuredInCommunity: true,
      creatorName: "Jessica Torres",
      creatorAvatar: null,
      status: "active" as const,
      budget: 40000,
      budgetBreakdown: [
        { category: "Brunch", amount: 15000, notes: "Brunch for 2 at local favorite" },
        { category: "Shopping & treats", amount: 10000, notes: "SoCo boutiques, ice cream, coffee" },
        { category: "Live music cover", amount: 10000, notes: "Entry to local venue" },
        { category: "Dinner & drinks", amount: 5000, notes: "Food truck and sunset cocktails" }
      ],
      budgetBuffer: 4000,
    },
    tasks: [
      { title: "Make brunch reservation at Matt's El Rancho", description: "Book 11am table for bottomless mimosas and Tex-Mex favorites", category: "personal", priority: "high" as const, timeEstimate: "10 min" },
      { title: "Enjoy leisurely brunch with friends", description: "Order the Famous Bob Armstrong Dip and catch up", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Walk off brunch at Zilker Park", description: "Frisbee, hammock time, or rent kayaks on Lady Bird Lake", category: "personal", priority: "high" as const, timeEstimate: "1.5 hours" },
      { title: "Explore South Congress boutiques and murals", description: "Allen's Boots, Uncommon Objects, 'I love you so much' wall", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Grab Amy's Ice Cream on South Congress", description: "Try Mexican Vanilla or seasonal flavor", category: "personal", priority: "medium" as const, timeEstimate: "20 min" },
      { title: "Check local music listings for evening show", description: "Continental Club, Antone's, or Mohawk for live music", category: "personal", priority: "high" as const, timeEstimate: "15 min" },
      { title: "Dinner at favorite food truck park", description: "East 6th Street or Rainey Street food options", category: "personal", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Catch sunset from Congress Avenue Bridge", description: "Watch bats emerge at dusk (seasonal)", category: "personal", priority: "medium" as const, timeEstimate: "45 min" },
      { title: "Enjoy live music at local venue", description: "Support Austin musicians and dance the night away", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Arrange safe ride home", description: "Uber, Lyft, or designated driver - never drink and drive", category: "personal", priority: "high" as const, timeEstimate: "20 min" },
    ]
  },
  {
    activity: {
      title: "Austin ACL Festival Weekend",
      description: "Epic 3-day Austin City Limits music festival with top artists and responsible celebration for Austin locals",
      category: "travel" as const,
      planSummary: "Austin local's ACL Festival guide with GA pass, festival essentials, food strategy, and safe transportation",
      isPublic: true,
      shareTitle: "Austin ACL Festival Weekend",
      backdrop: "/community-backdrops/acl_austin_city_limi_810a3c11.jpg",
      tags: ["acl", "austin", "music-festival", "live-music", "zilker-park", "weekend"],
      viewCount: 3200,
      likeCount: 2850,
      trendingScore: 6050,
      featuredInCommunity: true,
      creatorName: "David Chen",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 70000,
      budgetBreakdown: [
        { category: "3-day festival pass", amount: 35000, notes: "General admission wristband early bird" },
        { category: "Food & drinks", amount: 20000, notes: "Festival food vendors and hydration" },
        { category: "Transportation", amount: 10000, notes: "Bike to Zilker, rideshare backup" },
        { category: "Merch & extras", amount: 5000, notes: "Artist merchandise and festival gear" }
      ],
      budgetBuffer: 7000,
    },
    tasks: [
      { title: "Purchase ACL wristband during early bird sale", description: "Save $50-75 vs. regular price, register wristband immediately", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Study lineup and create personalized schedule", description: "Use ACL app to star must-see artists, plan stage rotations", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Pack festival survival kit", description: "Sunscreen SPF 50, portable charger, reusable water bottle, bandana, earplugs", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Prepare daily outfits for Austin heat", description: "Breathable fabrics, comfortable shoes, rain poncho (just in case)", category: "travel", priority: "medium" as const, timeEstimate: "30 min" },
      { title: "Day 1: Arrive early for premier headliner spots", description: "Claim shade, scope out stages, catch emerging artists", category: "travel", priority: "high" as const, timeEstimate: "10 hours" },
      { title: "Stay hydrated - refill water bottle every 90 min", description: "Free water stations throughout Zilker Park, avoid overheating", category: "travel", priority: "high" as const, timeEstimate: "ongoing" },
      { title: "Day 2 & 3: Balance top acts with rest breaks", description: "Don't burn out - find shade, eat real meals, pace yourself", category: "travel", priority: "high" as const, timeEstimate: "10 hours/day" },
      { title: "Coordinate group meeting spots and check-ins", description: "Cell service spotty - set specific times/locations to regroup", category: "travel", priority: "medium" as const, timeEstimate: "ongoing" },
      { title: "Use rideshare or walk home after festival ends", description: "Pre-schedule Uber/Lyft or coordinate group walking route - never drive impaired", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
    ]
  },
  {
    activity: {
      title: "Austin Formula 1 Race Weekend",
      description: "Premium F1 Grand Prix experience at Circuit of the Americas with hospitality, pit access, and VIP after-parties",
      category: "travel" as const,
      planSummary: "Ultimate Formula 1 weekend in Austin with grandstand tickets, paddock club access, downtown parties, and luxury transportation",
      isPublic: true,
      shareTitle: "Austin Formula 1 Race Weekend",
      backdrop: "/community-backdrops/formula_1_f1_race_ca_1ca5919d.jpg",
      tags: ["formula1", "f1", "racing", "austin", "cota", "luxury", "weekend"],
      viewCount: 2650,
      likeCount: 2280,
      trendingScore: 4930,
      featuredInCommunity: true,
      creatorName: "Alex Rodriguez",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 1800000,
      budgetBreakdown: [
        { category: "Race tickets", amount: 800000, notes: "Turn 12 grandstand seats, 3-day pass" },
        { category: "Hotel", amount: 500000, notes: "Downtown Austin hotel, 3 nights during race weekend" },
        { category: "Dining & entertainment", amount: 250000, notes: "Fine dining, F1 parties, rooftop bars" },
        { category: "Transportation", amount: 150000, notes: "Rideshares to COTA, black car service, surge pricing" },
        { category: "Paddock club upgrade", amount: 100000, notes: "One day VIP access with open bar and pit views" }
      ],
      budgetBuffer: 180000,
    },
    tasks: [
      { title: "Book F1 race tickets 6-8 months in advance", description: "Turn 12, Turn 15, or Main Grandstand for best racing action", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Reserve downtown Austin hotel near 6th Street", description: "Walking distance to bars, restaurants, and F1 fan events", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Friday: Practice sessions and explore COTA grounds", description: "Arrive early, tour expo village, watch teams setup", category: "travel", priority: "high" as const, timeEstimate: "8 hours" },
      { title: "Saturday: Qualifying day - arrive 2 hours early", description: "Watch drivers fight for pole position, crucial for Sunday", category: "travel", priority: "high" as const, timeEstimate: "7 hours" },
      { title: "Saturday night: Downtown F1 parties and celebrations", description: "6th Street takeover, team parties, rooftop bar scene", category: "travel", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Sunday: Race day - get to COTA by 11am", description: "Pre-race ceremonies, driver parade, national anthem", category: "travel", priority: "high" as const, timeEstimate: "8 hours" },
      { title: "Experience the race from premium grandstand seats", description: "56+ laps of high-speed racing, pit stop strategy, podium finish", category: "travel", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Post-race: Wait for traffic to clear, grab food", description: "Explore COTA vendors, avoid 2-hour parking lot nightmare", category: "travel", priority: "medium" as const, timeEstimate: "1.5 hours" },
      { title: "Sunday night: Victory celebrations downtown", description: "Watch winning team celebrate at sponsored events and bars", category: "travel", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Arrange safe transportation throughout weekend", description: "Pre-book rideshares, designated drivers, or black car service - surge pricing expected", category: "travel", priority: "high" as const, timeEstimate: "ongoing" },
    ]
  },
  {
    activity: {
      title: "Austin SXSW Music & Tech Festival",
      description: "Navigate South by Southwest with badge strategy, must-see showcases, and party-hopping for Austin locals",
      category: "travel" as const,
      planSummary: "Local's SXSW survival guide: badge options, showcase priorities, free parties, and budget-friendly strategies",
      isPublic: true,
      shareTitle: "Austin SXSW Music & Tech Festival",
      backdrop: "/community-backdrops/sxsw_south_by_southw_e754d975.jpg",
      tags: ["sxsw", "austin", "music", "tech", "film", "networking", "festival"],
      viewCount: 2890,
      likeCount: 2450,
      trendingScore: 5340,
      featuredInCommunity: true,
      creatorName: "Taylor Morrison",
      creatorAvatar: null,
      status: "planning" as const,
      budget: 180000,
      budgetBreakdown: [
        { category: "SXSW wristband", amount: 95000, notes: "Music wristband early bird pricing" },
        { category: "Food & drinks", amount: 50000, notes: "Food trucks, tacos, free sponsored parties" },
        { category: "Transportation", amount: 20000, notes: "Bike around downtown, occasional rideshares" },
        { category: "Merch & extras", amount: 15000, notes: "Artist merchandise, limited releases" }
      ],
      budgetBuffer: 18000,
    },
    tasks: [
      { title: "Purchase SXSW wristband during early bird pricing", description: "Wristband offers best value for showcase access at local prices", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Download SXSW app and build personal schedule", description: "Star priority shows, set alerts for RSVP opens, note conflicting times", category: "travel", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Research RSVP-only day parties and activations", description: "Spotify House, NPR Showcase, Hype Hotel - RSVP opens 2 weeks before", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Plan daily strategy: panels + showcases + parties", description: "Balance conference sessions, official showcases, unofficial events", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Pack for Austin's unpredictable March weather", description: "Layers, rain jacket, comfortable walking shoes for 6+ miles/day", category: "travel", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Navigate badge vs. wristband vs. RSVP hierarchy", description: "Learn venue priority system, arrive early for popular acts", category: "travel", priority: "medium" as const, timeEstimate: "ongoing" },
      { title: "Attend 2-3 showcases per night, pace yourself", description: "Don't burn out on day 1 - it's a marathon, not a sprint", category: "travel", priority: "high" as const, timeEstimate: "ongoing" },
      { title: "Network at day parties and industry mixers", description: "Bring business cards, connect on LinkedIn, exchange contacts", category: "travel", priority: "medium" as const, timeEstimate: "ongoing" },
      { title: "Stay safe while venue-hopping late night", description: "Travel in groups, use rideshares for long distances, stay hydrated, know your limits", category: "travel", priority: "high" as const, timeEstimate: "ongoing" },
    ]
  }
];
