import type { InsertActivity, InsertTask } from "@shared/schema";

// Demo community plans with high-quality stock images
export const demoCommunityPlans = [
  {
    activity: {
      title: "Weekend Trip to Paris",
      description: "Complete 3-day Paris itinerary with sights, dining, and Eiffel Tower visit",
      category: "travel" as const,
      planSummary: "Romantic 3-day Paris escape with iconic landmarks, French cuisine, and evening river cruise",
      isPublic: true,
      shareTitle: "Weekend Trip to Paris",
      backdrop: "romantic_paris_citys_dfc7c798.jpg",
      tags: ["travel", "paris", "europe", "weekend", "romantic"],
      viewCount: 2400,
      likeCount: 2400,
      trendingScore: 4800,
      featuredInCommunity: true,
      creatorName: "Sarah Chen",
      creatorAvatar: null,
      status: "completed" as const,
    },
    tasks: [
      { title: "Book hotel in Le Marais district", description: "Boutique hotel near Metro", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Visit Eiffel Tower at sunset", description: "Book tickets in advance to skip lines", category: "travel", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Explore Louvre Museum", description: "See Mona Lisa and Egyptian exhibits", category: "travel", priority: "high" as const, timeEstimate: "4 hours" },
      { title: "Seine River dinner cruise", description: "Evening cruise with French dinner", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Stroll through Montmartre", description: "Visit Sacré-Cœur and artist square", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "30-Day Fitness Challenge",
      description: "Daily workouts, meal prep, and progress tracking for complete transformation",
      category: "health" as const,
      planSummary: "Structured 30-day fitness program with workouts, nutrition plan, and accountability tracking",
      isPublic: true,
      shareTitle: "30-Day Fitness Challenge",
      backdrop: "fitness_workout_gym__2325ee98.jpg",
      tags: ["fitness", "health", "workout", "challenge", "30days"],
      viewCount: 1800,
      likeCount: 1800,
      trendingScore: 3600,
      featuredInCommunity: true,
      creatorName: "Mike Johnson",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Week 1: Build foundation with bodyweight exercises", description: "Push-ups, squats, planks", category: "health", priority: "high" as const, timeEstimate: "45 min" },
      { title: "Meal prep healthy breakfast options", description: "Overnight oats, egg muffins, smoothie packs", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Week 2: Add resistance training", description: "Dumbbells and resistance bands", category: "health", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Track daily water intake (64oz)", description: "Use water tracking app", category: "health", priority: "medium" as const, timeEstimate: "5 min" },
      { title: "Weekly progress photos and measurements", description: "Track body composition changes", category: "health", priority: "medium" as const, timeEstimate: "10 min" },
    ]
  },
  {
    activity: {
      title: "Wedding Planning Checklist",
      description: "12-month wedding plan with venue, vendors, guests, and timeline",
      category: "personal" as const,
      planSummary: "Complete wedding planning guide covering venue booking, vendor selection, and timeline management",
      isPublic: true,
      shareTitle: "Wedding Planning Checklist",
      backdrop: "elegant_wedding_cere_9aa2c585.jpg",
      tags: ["wedding", "planning", "events", "checklist", "celebration"],
      viewCount: 3200,
      likeCount: 3200,
      trendingScore: 6400,
      featuredInCommunity: true,
      creatorName: "Emma Davis",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Set wedding budget and priorities", description: "Allocate funds across venue, catering, photography", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Book wedding venue (12 months out)", description: "Visit 3-5 venues, secure date", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Hire photographer and videographer", description: "Review portfolios, book 9-12 months ahead", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Finalize guest list and send save-the-dates", description: "Confirm addresses, design and mail STDs", category: "personal", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Schedule dress fittings and alterations", description: "Order dress 8-10 months out, fittings begin", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Career Switch to Tech",
      description: "6-month plan: coding bootcamp, portfolio projects, and job applications",
      category: "work" as const,
      planSummary: "Comprehensive career transition roadmap from non-tech to software development role",
      isPublic: true,
      shareTitle: "Career Switch to Tech",
      backdrop: "modern_tech_workspac_ef8fa108.jpg",
      tags: ["career", "tech", "coding", "bootcamp", "transition"],
      viewCount: 1500,
      likeCount: 1500,
      trendingScore: 3000,
      featuredInCommunity: false,
      creatorName: "Alex Kim",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Complete JavaScript fundamentals course", description: "FreeCodeCamp or Codecademy basics", category: "work", priority: "high" as const, timeEstimate: "40 hours" },
      { title: "Enroll in coding bootcamp (online or in-person)", description: "Research reviews, apply for scholarships", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Build 3 portfolio projects", description: "Full-stack apps showcasing skills", category: "work", priority: "high" as const, timeEstimate: "3 months" },
      { title: "Network with developers on LinkedIn", description: "Join tech communities, attend meetups", category: "work", priority: "medium" as const, timeEstimate: "1 hour/week" },
      { title: "Apply to junior developer positions", description: "Tailor resume, practice interviews", category: "work", priority: "high" as const, timeEstimate: "4 weeks" },
    ]
  },
  {
    activity: {
      title: "Home Renovation Project",
      description: "Kitchen remodel: contractors, materials, permits, and budget tracking",
      category: "personal" as const,
      planSummary: "Step-by-step kitchen renovation with contractor management and budget control",
      isPublic: true,
      shareTitle: "Home Renovation Project",
      backdrop: "beautiful_modern_hom_0f24a3e6.jpg",
      tags: ["home", "renovation", "remodel", "diy", "kitchen"],
      viewCount: 2100,
      likeCount: 2100,
      trendingScore: 4200,
      featuredInCommunity: true,
      creatorName: "Lisa Park",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Get 3 contractor quotes", description: "Licensed, insured, with references", category: "personal", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Apply for renovation permits", description: "Submit plans to city planning dept", category: "personal", priority: "high" as const, timeEstimate: "1 week" },
      { title: "Order cabinets and countertops", description: "Measure precisely, order 8-10 weeks ahead", category: "personal", priority: "high" as const, timeEstimate: "4 hours" },
      { title: "Select appliances and fixtures", description: "Refrigerator, stove, sink, lighting", category: "personal", priority: "medium" as const, timeEstimate: "3 hours" },
      { title: "Schedule inspections post-renovation", description: "Electrical, plumbing, final walkthrough", category: "personal", priority: "medium" as const, timeEstimate: "1 hour" },
    ]
  },
  {
    activity: {
      title: "Master Productivity System",
      description: "Daily routines, time blocking, and focus techniques for peak performance",
      category: "work" as const,
      planSummary: "Evidence-based productivity framework combining time management and deep work principles",
      isPublic: true,
      shareTitle: "Master Productivity System",
      backdrop: "organized_productivi_df70e725.jpg",
      tags: ["productivity", "time-management", "focus", "routine", "work"],
      viewCount: 890,
      likeCount: 890,
      trendingScore: 1780,
      featuredInCommunity: false,
      creatorName: "David Lee",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Implement morning routine (5:30 AM start)", description: "Exercise, meditation, journaling", category: "work", priority: "high" as const, timeEstimate: "90 min" },
      { title: "Time-block calendar for deep work", description: "4-hour blocks for focused tasks", category: "work", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Use Pomodoro technique (25 min focus)", description: "Work in focused sprints with breaks", category: "work", priority: "high" as const, timeEstimate: "25 min" },
      { title: "Weekly review and planning session", description: "Reflect on wins, plan next week", category: "work", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Eliminate digital distractions", description: "Block social media during work hours", category: "work", priority: "medium" as const, timeEstimate: "15 min" },
    ]
  },
  {
    activity: {
      title: "Digital Nomad Guide to Bali",
      description: "Remote work paradise: visa, coworking spaces, best neighborhoods, and scooter rentals",
      category: "travel" as const,
      planSummary: "Complete guide for remote workers relocating to Bali with workspace, visa, and living tips",
      isPublic: true,
      shareTitle: "Digital Nomad Guide to Bali",
      backdrop: "bali_indonesia_tropi_95575be5.jpg",
      tags: ["travel", "bali", "digital-nomad", "remote-work", "asia"],
      viewCount: 1950,
      likeCount: 1650,
      trendingScore: 3600,
      featuredInCommunity: true,
      creatorName: "Jordan Rivera",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Apply for B211A visa (60 days)", description: "Required documents and embassy appointment", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Book Airbnb in Canggu or Ubud", description: "Near coworking spaces with fast WiFi", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Join Dojo Bali or Hubud coworking", description: "Monthly membership for reliable internet", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Rent scooter and get international license", description: "Essential for island mobility", category: "travel", priority: "medium" as const, timeEstimate: "3 hours" },
      { title: "Set up Indonesian bank account", description: "For local payments and withdrawals", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Marathon Training: 16-Week Plan",
      description: "First-time marathoner? Build endurance from 5K to 26.2 miles with injury prevention",
      category: "health" as const,
      planSummary: "Structured 16-week training program with progressive mileage, nutrition, and recovery strategies",
      isPublic: true,
      shareTitle: "Marathon Training: 16-Week Plan",
      backdrop: "runner_jogging_on_tr_9a63ddad.jpg",
      tags: ["fitness", "running", "marathon", "training", "endurance"],
      viewCount: 2850,
      likeCount: 2400,
      trendingScore: 5250,
      featuredInCommunity: true,
      creatorName: "Rachel Martinez",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Weeks 1-4: Build base (20-30 miles/week)", description: "Easy pace with one long run", category: "health", priority: "high" as const, timeEstimate: "6 hours/week" },
      { title: "Get fitted for proper running shoes", description: "Visit running specialty store for gait analysis", category: "health", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Weeks 5-8: Add tempo runs (35-40 miles/week)", description: "Increase pace on mid-week runs", category: "health", priority: "high" as const, timeEstimate: "7 hours/week" },
      { title: "Practice race-day nutrition strategy", description: "Test gels, hydration during long runs", category: "health", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Weeks 12-16: Taper and race prep", description: "Reduce mileage, rest, carb load", category: "health", priority: "medium" as const, timeEstimate: "4 hours/week" },
    ]
  },
  {
    activity: {
      title: "Tokyo Adventure: 7-Day Itinerary",
      description: "Shibuya crossing, Mt. Fuji day trip, ramen tours, and hidden temples",
      category: "travel" as const,
      planSummary: "Week-long Tokyo exploration blending modern culture, traditional sites, and culinary experiences",
      isPublic: true,
      shareTitle: "Tokyo Adventure: 7-Day Itinerary",
      backdrop: "tokyo_japan_travel_d_8a196170.jpg",
      tags: ["travel", "tokyo", "japan", "culture", "food"],
      viewCount: 3400,
      likeCount: 2900,
      trendingScore: 6300,
      featuredInCommunity: true,
      creatorName: "Kenji Tanaka",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Get JR Rail Pass (7-day)", description: "Order online 2 weeks before trip", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Day 1: Shibuya & Harajuku exploration", description: "Scramble crossing, Meiji Shrine, Takeshita Street", category: "travel", priority: "high" as const, timeEstimate: "8 hours" },
      { title: "Day 3: Mt. Fuji day trip from Shinjuku", description: "Early morning bus to 5th station", category: "travel", priority: "high" as const, timeEstimate: "12 hours" },
      { title: "Reserve TeamLab Borderless tickets", description: "Digital art museum, book weeks ahead", category: "travel", priority: "medium" as const, timeEstimate: "30 min" },
      { title: "Day 5: Tsukiji Market breakfast & Senso-ji Temple", description: "Fresh sushi and traditional shopping", category: "travel", priority: "medium" as const, timeEstimate: "6 hours" },
    ]
  },
  {
    activity: {
      title: "Launch Your Side Hustle",
      description: "Validate idea, build MVP, get first 10 customers in 90 days",
      category: "work" as const,
      planSummary: "Practical startup framework from idea validation to revenue generation in 3 months",
      isPublic: true,
      shareTitle: "Launch Your Side Hustle",
      backdrop: "modern_workspace_des_9f6c2608.jpg",
      tags: ["entrepreneurship", "startup", "side-hustle", "business", "revenue"],
      viewCount: 1750,
      likeCount: 1500,
      trendingScore: 3250,
      featuredInCommunity: true,
      creatorName: "Priya Sharma",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Validate idea with 20 customer interviews", description: "Talk to target customers about pain points", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
      { title: "Build landing page with email capture", description: "Use Carrd or Webflow, test messaging", category: "work", priority: "high" as const, timeEstimate: "8 hours" },
      { title: "Create MVP in 2-3 weeks", description: "Minimum viable product, not perfect", category: "work", priority: "high" as const, timeEstimate: "40 hours" },
      { title: "Run small paid ads campaign ($200 budget)", description: "Facebook or Google Ads to test demand", category: "work", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Reach out to first 100 potential customers", description: "Email, LinkedIn, Twitter DMs", category: "work", priority: "high" as const, timeEstimate: "2 weeks" },
    ]
  },
  {
    activity: {
      title: "Master Public Speaking",
      description: "Overcome stage fright, craft compelling talks, and deliver with confidence",
      category: "work" as const,
      planSummary: "8-week public speaking mastery program with Toastmasters, speech writing, and TEDx prep",
      isPublic: true,
      shareTitle: "Master Public Speaking",
      backdrop: "business_presentatio_aee687af.jpg",
      tags: ["public-speaking", "communication", "career", "confidence", "presentation"],
      viewCount: 1320,
      likeCount: 1100,
      trendingScore: 2420,
      featuredInCommunity: false,
      creatorName: "Marcus Thompson",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Join local Toastmasters club", description: "Attend meetings twice monthly for practice", category: "work", priority: "high" as const, timeEstimate: "2 hours/meeting" },
      { title: "Record yourself giving 3 practice speeches", description: "Review body language and vocal patterns", category: "work", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Write and memorize signature talk (10 min)", description: "Use storytelling framework", category: "work", priority: "high" as const, timeEstimate: "12 hours" },
      { title: "Practice power poses before speaking", description: "Amy Cuddy's confidence technique", category: "work", priority: "medium" as const, timeEstimate: "5 min" },
      { title: "Apply to speak at local meetups or conferences", description: "Start small, build experience", category: "work", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "NYC Holiday Magic: Christmas Week",
      description: "Rockefeller tree, ice skating, Broadway shows, and holiday markets",
      category: "travel" as const,
      planSummary: "Festive New York City experience with iconic holiday traditions and winter activities",
      isPublic: true,
      shareTitle: "NYC Holiday Magic: Christmas Week",
      backdrop: "new_york_city_times__e09e766b.jpg",
      tags: ["travel", "nyc", "christmas", "holiday", "winter"],
      viewCount: 2650,
      likeCount: 2200,
      trendingScore: 4850,
      featuredInCommunity: true,
      creatorName: "Amanda Collins",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Book Broadway show tickets (Hamilton or Wicked)", description: "Reserve 2-3 months ahead for holiday dates", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Visit Rockefeller Center Christmas Tree", description: "See tree lighting or visit early morning", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Ice skate at Bryant Park (free admission)", description: "Bring warm clothes, rent skates on-site", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Explore holiday markets (Union Square, Columbus Circle)", description: "Shop for gifts and hot chocolate", category: "travel", priority: "medium" as const, timeEstimate: "3 hours" },
      { title: "Walk through Dyker Heights Christmas lights (Brooklyn)", description: "Over-the-top neighborhood decorations", category: "travel", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Mindfulness & Meditation Practice",
      description: "21-day habit builder with guided sessions, breathwork, and journaling",
      category: "health" as const,
      planSummary: "Structured meditation program for beginners to establish daily mindfulness routine",
      isPublic: true,
      shareTitle: "Mindfulness & Meditation Practice",
      backdrop: "yoga_studio_peaceful_84f9a366.jpg",
      tags: ["mindfulness", "meditation", "mental-health", "wellness", "habit"],
      viewCount: 1580,
      likeCount: 1320,
      trendingScore: 2900,
      featuredInCommunity: true,
      creatorName: "Elena Rodriguez",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Days 1-7: 5-minute morning meditation", description: "Use Headspace or Calm app", category: "health", priority: "high" as const, timeEstimate: "5 min/day" },
      { title: "Set up meditation space at home", description: "Quiet corner with cushion, minimal distractions", category: "health", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Days 8-14: Add breathwork (box breathing)", description: "4-4-4-4 pattern for stress relief", category: "health", priority: "high" as const, timeEstimate: "10 min/day" },
      { title: "Keep gratitude journal (evening)", description: "Write 3 things daily", category: "health", priority: "medium" as const, timeEstimate: "5 min/day" },
      { title: "Days 15-21: Extend to 15-minute sessions", description: "Deepen practice, notice improvements", category: "health", priority: "medium" as const, timeEstimate: "15 min/day" },
    ]
  },
  {
    activity: {
      title: "Iceland Northern Lights Expedition",
      description: "Chase aurora borealis, explore ice caves, and relax in Blue Lagoon",
      category: "travel" as const,
      planSummary: "5-day Iceland adventure focusing on Northern Lights photography and natural wonders",
      isPublic: true,
      shareTitle: "Iceland Northern Lights Expedition",
      backdrop: "iceland_northern_lig_9fbbf14d.jpg",
      tags: ["travel", "iceland", "northern-lights", "adventure", "photography"],
      viewCount: 2190,
      likeCount: 1850,
      trendingScore: 4040,
      featuredInCommunity: true,
      creatorName: "Stefan Olafsson",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Book trip between September-March", description: "Peak aurora season with longer nights", category: "travel", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Rent 4WD vehicle for Ring Road drive", description: "Essential for winter road conditions", category: "travel", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Reserve Blue Lagoon premium entry", description: "Book weeks ahead, go at sunset", category: "travel", priority: "high" as const, timeEstimate: "30 min" },
      { title: "Download Aurora forecast app", description: "Track KP index and cloud cover", category: "travel", priority: "medium" as const, timeEstimate: "15 min" },
      { title: "Join guided ice cave tour in Vatnajökull", description: "Safe exploration with expert guides", category: "travel", priority: "medium" as const, timeEstimate: "4 hours" },
    ]
  },
  {
    activity: {
      title: "Cycling Century Ride: 100-Mile Challenge",
      description: "12-week training plan from 20 miles to 100-mile century ride",
      category: "health" as const,
      planSummary: "Progressive cycling program building endurance for first 100-mile ride with nutrition tips",
      isPublic: true,
      shareTitle: "Cycling Century Ride: 100-Mile Challenge",
      backdrop: "cyclist_riding_bike__9ae17ca2.jpg",
      tags: ["cycling", "fitness", "endurance", "challenge", "training"],
      viewCount: 1240,
      likeCount: 1050,
      trendingScore: 2290,
      featuredInCommunity: false,
      creatorName: "Tyler Chen",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Weeks 1-4: Build base (50-70 miles/week)", description: "3-4 rides with progressive distance", category: "health", priority: "high" as const, timeEstimate: "6 hours/week" },
      { title: "Get professional bike fit", description: "Prevent injury, improve efficiency", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Weeks 5-8: Add interval training", description: "Hill repeats and tempo rides", category: "health", priority: "high" as const, timeEstimate: "7 hours/week" },
      { title: "Practice nutrition strategy on long rides", description: "Test energy bars, electrolytes", category: "health", priority: "medium" as const, timeEstimate: "1 hour" },
      { title: "Weeks 10-12: Peak with 80-mile ride, then taper", description: "Final long ride 2 weeks before century", category: "health", priority: "medium" as const, timeEstimate: "8 hours" },
    ]
  },
  {
    activity: {
      title: "Strength Training for Beginners",
      description: "8-week progressive overload program with compound movements",
      category: "health" as const,
      planSummary: "Science-based strength program teaching squat, deadlift, bench press, and overhead press fundamentals",
      isPublic: true,
      shareTitle: "Strength Training for Beginners",
      backdrop: "modern_gym_workout_w_99dc5406.jpg",
      tags: ["fitness", "strength-training", "gym", "muscle", "beginner"],
      viewCount: 2050,
      likeCount: 1750,
      trendingScore: 3800,
      featuredInCommunity: true,
      creatorName: "Chris Anderson",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Learn proper form for big 4 lifts", description: "Squat, deadlift, bench, overhead press - watch videos", category: "health", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Start with empty barbell (45 lbs)", description: "Master form before adding weight", category: "health", priority: "high" as const, timeEstimate: "3 sessions" },
      { title: "Follow 3x/week full-body program", description: "Monday/Wednesday/Friday schedule", category: "health", priority: "high" as const, timeEstimate: "1 hour/session" },
      { title: "Track lifts in fitness app", description: "Progressive overload: add 5 lbs weekly", category: "health", priority: "medium" as const, timeEstimate: "10 min" },
      { title: "Eat in caloric surplus (300-500 cals)", description: "Support muscle growth with protein", category: "health", priority: "medium" as const, timeEstimate: "daily" },
    ]
  },
  {
    activity: {
      title: "Professional Networking Strategy",
      description: "Build genuine relationships, attend industry events, and grow LinkedIn presence",
      category: "work" as const,
      planSummary: "90-day networking plan to expand professional connections and unlock career opportunities",
      isPublic: true,
      shareTitle: "Professional Networking Strategy",
      backdrop: "professional_network_48ccc448.jpg",
      tags: ["networking", "career", "linkedin", "professional-development", "relationships"],
      viewCount: 1450,
      likeCount: 1200,
      trendingScore: 2650,
      featuredInCommunity: true,
      creatorName: "Jennifer Wong",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Optimize LinkedIn profile with keywords", description: "Professional photo, compelling headline", category: "work", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Attend 2 industry meetups monthly", description: "Find events on Meetup.com or Eventbrite", category: "work", priority: "high" as const, timeEstimate: "4 hours/month" },
      { title: "Send 5 personalized connection requests weekly", description: "Reference shared interests or mutual connections", category: "work", priority: "high" as const, timeEstimate: "30 min/week" },
      { title: "Schedule 2 coffee chats monthly", description: "Informational interviews with industry pros", category: "work", priority: "medium" as const, timeEstimate: "2 hours/month" },
      { title: "Share valuable content on LinkedIn (2x/week)", description: "Industry insights, personal experiences", category: "work", priority: "medium" as const, timeEstimate: "30 min/week" },
    ]
  },
  {
    activity: {
      title: "Personal Reading Challenge: 52 Books",
      description: "One book per week with diverse genres, discussion groups, and reflection journal",
      category: "personal" as const,
      planSummary: "Year-long reading habit with curated book list, tracking system, and community engagement",
      isPublic: true,
      shareTitle: "Personal Reading Challenge: 52 Books",
      backdrop: "person_reading_book__bc916131.jpg",
      tags: ["reading", "books", "personal-growth", "learning", "habit"],
      viewCount: 1680,
      likeCount: 1400,
      trendingScore: 3080,
      featuredInCommunity: true,
      creatorName: "Olivia Brown",
      creatorAvatar: null,
      status: "active" as const,
    },
    tasks: [
      { title: "Create reading list with genre variety", description: "Fiction, non-fiction, biography, self-help mix", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Set daily reading time (30 min before bed)", description: "Consistent habit, no phone", category: "personal", priority: "high" as const, timeEstimate: "30 min/day" },
      { title: "Join Goodreads and book club community", description: "Track progress, get recommendations", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Write reflection notes after each book", description: "Key takeaways, favorite quotes", category: "personal", priority: "medium" as const, timeEstimate: "20 min/book" },
      { title: "Visit library or use Libby app", description: "Free access to audiobooks and ebooks", category: "personal", priority: "medium" as const, timeEstimate: "1 hour" },
    ]
  },
  {
    activity: {
      title: "Epic Birthday Party: 30th Celebration",
      description: "Venue, theme, guest list, catering, entertainment, and surprise moments",
      category: "personal" as const,
      planSummary: "Complete party planning guide for milestone birthday with 50-80 guests",
      isPublic: true,
      shareTitle: "Epic Birthday Party: 30th Celebration",
      backdrop: "birthday_party_celeb_414d649e.jpg",
      tags: ["birthday", "party", "celebration", "event-planning", "milestone"],
      viewCount: 1890,
      likeCount: 1600,
      trendingScore: 3490,
      featuredInCommunity: true,
      creatorName: "Michael Torres",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Book venue 2-3 months ahead", description: "Restaurant private room or event space", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Choose party theme (decade, tropical, casino)", description: "Coordinate decor and dress code", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Send digital invitations (Paperless Post)", description: "RSVP deadline 2 weeks before", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Arrange catering or food stations", description: "Consider dietary restrictions", category: "personal", priority: "medium" as const, timeEstimate: "4 hours" },
      { title: "Plan surprise element or entertainment", description: "DJ, photo booth, or special performance", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
    ]
  },
  {
    activity: {
      title: "Music Festival Survival Guide",
      description: "Packing list, camping setup, schedule planning, and festival hacks",
      category: "personal" as const,
      planSummary: "Complete preparation guide for multi-day music festival with camping tips and safety essentials",
      isPublic: true,
      shareTitle: "Music Festival Survival Guide",
      backdrop: "concert_music_festiv_18316657.jpg",
      tags: ["festival", "music", "camping", "travel", "events"],
      viewCount: 2340,
      likeCount: 1950,
      trendingScore: 4290,
      featuredInCommunity: true,
      creatorName: "Sophie Anderson",
      creatorAvatar: null,
      status: "planning" as const,
    },
    tasks: [
      { title: "Pack festival essentials kit", description: "Tent, sleeping bag, portable charger, sunscreen", category: "personal", priority: "high" as const, timeEstimate: "3 hours" },
      { title: "Review lineup and create set schedule", description: "Prioritize must-see artists, plan conflicts", category: "personal", priority: "high" as const, timeEstimate: "2 hours" },
      { title: "Prepare hydration and food strategy", description: "Reusable water bottle, energy bars, cashless payment", category: "personal", priority: "high" as const, timeEstimate: "1 hour" },
      { title: "Set up camp in shaded area early", description: "Arrive Thursday to secure good spot", category: "personal", priority: "medium" as const, timeEstimate: "2 hours" },
      { title: "Coordinate meeting spots with friends", description: "Cell service unreliable, plan meetup times/locations", category: "personal", priority: "medium" as const, timeEstimate: "30 min" },
    ]
  }
];
