import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  TrendingUp, TrendingDown, Heart, Target, Brain,
  Calendar, Award, Sparkles, Crown, Lock, BarChart3
} from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';

interface InsightsDashboardProps {
  onClose?: () => void;
  onUpgradeRequired?: () => void;
}

interface InsightsData {
  moodTrend: 'improving' | 'stable' | 'declining';
  completionRate: number;
  mostLovedCategories: Array<{ category: string; count: number }>;
  productivityPattern: string;
  weeklyStreak: number;
  aiSummary: string;
  totalEntries: number;
  totalActivities: number;
  totalTasksCompleted: number;
}

export default function InsightsDashboard({ onClose, onUpgradeRequired }: InsightsDashboardProps) {
  const { user } = useAuth();
  const isPro = user?.subscriptionTier === 'pro' || user?.subscriptionTier === 'family';

  // Fetch insights data
  const { data: insights, isLoading } = useQuery<InsightsData>({
    queryKey: ['/api/insights'],
    enabled: isPro,
  });

  if (!isPro) {
    return (
      <div className="flex flex-col h-full items-center justify-center p-8">
        <div className="max-w-md text-center space-y-6">
          <div className="mx-auto w-20 h-20 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
            <Lock className="w-10 h-10 text-white" />
          </div>

          <div className="space-y-2">
            <h2 className="text-2xl font-bold">Unlock AI-Powered Insights</h2>
            <p className="text-muted-foreground">
              Get personalized analytics on your productivity, mood trends, and task patterns with AI-generated weekly summaries.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4 text-left">
            <Card className="border-purple-200 dark:border-purple-800">
              <CardHeader className="pb-3">
                <TrendingUp className="w-6 h-6 text-purple-500 mb-2" />
                <CardTitle className="text-sm">Mood Trends</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs text-muted-foreground">Track your emotional patterns over time</p>
              </CardContent>
            </Card>

            <Card className="border-purple-200 dark:border-purple-800">
              <CardHeader className="pb-3">
                <Target className="w-6 h-6 text-purple-500 mb-2" />
                <CardTitle className="text-sm">Task Analytics</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs text-muted-foreground">Discover your most productive patterns</p>
              </CardContent>
            </Card>

            <Card className="border-purple-200 dark:border-purple-800">
              <CardHeader className="pb-3">
                <Heart className="w-6 h-6 text-purple-500 mb-2" />
                <CardTitle className="text-sm">Love Patterns</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs text-muted-foreground">See what activities bring you joy</p>
              </CardContent>
            </Card>

            <Card className="border-purple-200 dark:border-purple-800">
              <CardHeader className="pb-3">
                <Brain className="w-6 h-6 text-purple-500 mb-2" />
                <CardTitle className="text-sm">AI Summaries</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs text-muted-foreground">Weekly insights generated by AI</p>
              </CardContent>
            </Card>
          </div>

          <Button onClick={onUpgradeRequired} size="lg" className="w-full">
            <Crown className="w-4 h-4 mr-2" />
            Upgrade to Pro
          </Button>
        </div>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center space-y-4">
          <div className="animate-spin mx-auto w-12 h-12 border-4 border-primary border-t-transparent rounded-full" />
          <p className="text-muted-foreground">Analyzing your data...</p>
        </div>
      </div>
    );
  }

  return (
    <ScrollArea className="h-full">
      <div className="p-6 space-y-6">
        {/* Header */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <h1 className="text-3xl font-bold">Your Insights</h1>
            <Badge variant="secondary" className="bg-gradient-to-r from-purple-500 to-pink-500 text-white border-none">
              <Crown className="w-3 h-3 mr-1" />
              Pro
            </Badge>
          </div>
          <p className="text-muted-foreground">
            AI-powered analytics based on your journal, tasks, and activities
          </p>
        </div>

        {/* Stats Overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Total Journal Entries</CardDescription>
              <CardTitle className="text-3xl">{insights?.totalEntries || 0}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground">Across all categories</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Activities Created</CardDescription>
              <CardTitle className="text-3xl">{insights?.totalActivities || 0}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground">Plans and goals</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2">
              <CardDescription>Tasks Completed</CardDescription>
              <CardTitle className="text-3xl">{insights?.totalTasksCompleted || 0}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground">
                {insights?.completionRate || 0}% completion rate
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Mood Trend */}
        <Card className="border-2">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                {insights?.moodTrend === 'improving' && <TrendingUp className="w-5 h-5 text-green-500" />}
                {insights?.moodTrend === 'stable' && <BarChart3 className="w-5 h-5 text-blue-500" />}
                {insights?.moodTrend === 'declining' && <TrendingDown className="w-5 h-5 text-orange-500" />}
                Mood Trend
              </CardTitle>
              <Badge
                variant={insights?.moodTrend === 'improving' ? 'default' : insights?.moodTrend === 'stable' ? 'secondary' : 'destructive'}
              >
                {insights?.moodTrend || 'Unknown'}
              </Badge>
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              {insights?.moodTrend === 'improving' &&
                "Your mood has been trending upward! Keep up the great work. 🌟"}
              {insights?.moodTrend === 'stable' &&
                "Your mood has been consistent. Consider exploring new activities for variety."}
              {insights?.moodTrend === 'declining' &&
                "We've noticed your mood trending down. Remember to take care of yourself. 💙"}
            </p>
          </CardContent>
        </Card>

        {/* Most Loved Categories */}
        {insights?.mostLovedCategories && insights.mostLovedCategories.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Heart className="w-5 h-5 text-red-500" />
                What You Love Most
              </CardTitle>
              <CardDescription>
                Categories with the most ❤️ Superlike reactions
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {insights.mostLovedCategories.slice(0, 5).map((item, index) => (
                  <div key={index} className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="flex items-center justify-center w-8 h-8 rounded-full bg-gradient-to-br from-red-500 to-pink-500 text-white text-sm font-bold">
                        {index + 1}
                      </div>
                      <span className="font-medium">{item.category}</span>
                    </div>
                    <Badge variant="outline">{item.count} ❤️</Badge>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Productivity Pattern */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="w-5 h-5 text-blue-500" />
              Productivity Pattern
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm">
              {insights?.productivityPattern || "Complete more tasks to see your productivity pattern!"}
            </p>
          </CardContent>
        </Card>

        {/* Weekly Streak */}
        <Card className="bg-gradient-to-br from-orange-50 to-yellow-50 dark:from-orange-950/20 dark:to-yellow-950/20 border-orange-200 dark:border-orange-800">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Award className="w-5 h-5 text-orange-500" />
              Weekly Streak
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-4">
              <div className="text-4xl font-bold text-orange-500">
                {insights?.weeklyStreak || 0}
              </div>
              <div>
                <p className="font-medium">Days active this week</p>
                <p className="text-sm text-muted-foreground">
                  {insights?.weeklyStreak === 7
                    ? "Perfect week! 🎉"
                    : insights?.weeklyStreak && insights.weeklyStreak >= 5
                    ? "Impressive consistency!"
                    : "Keep building your streak!"}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* AI-Generated Summary */}
        {insights?.aiSummary && (
          <Card className="border-2 border-primary/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary" />
                AI-Generated Weekly Summary
              </CardTitle>
              <CardDescription>Based on your journal and activity data</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed whitespace-pre-wrap">
                {insights.aiSummary}
              </p>
            </CardContent>
          </Card>
        )}
      </div>
    </ScrollArea>
  );
}
